### ISSUE TITLE
Passing request_pos through source wrappers

### ISSUE THREAD

**Issue by dvdsk** [dvdsk/rodio#1]
For example DataConverter is used by UniformSourceIterator which implements Source. We should still be able to seek in a UniformSourceIterator however to pass the seek call to the underlying DataConverter either the input field must be made accessible or a public api must be added

**Comment by dskleingeld** [comment]
Limiting the this problem by defining a new trait `SourceExt` and then implementing it for only the bare minimum amount of Sources:

- [ ] Stoppable
- [ ] Amplify
- [ ] Pausable
- [ ] Mp3Decoder

**Comment by dskleingeld** [comment]
Mp3Decoder has no seek support yet, these is some work on https://github.com/Cocalus/minimp3-rs however not enough to get it running with rodio.

Working on minimp3-rs here: https://github.com/dskleingeld/minimp3-rs

**Comment by dskleingeld** [comment]
Seek is supported in minimp3, after `mp3dec_ex_seek` call `mp3dec_ex_read_frame` to read a frame again. Bindings/wrapper needs to be updated/created. Its kinda a mess currently. 

- [ ] create separate module in https://github.com/dskleingeld/minimp3-rs for the higher level mp3dec_ex api
- [ ] clean up the current lib.rs file
- [ ] rewrite rodio Mp3Decoder to use the new higher level mp3dec_ex api, taking care to reset frame after seeking
